### PR TITLE
perf: optimize activationEvents

### PR DESCRIPTION
**Pull request by tjx666**
#820

### CODE REVIEW

**Comment by tjx666** [comment]
I find the souce code is not very many, but the project typescript intellisence is very slow, don't konw why.

**Comment by nicoespeon** [comment]
Interesting. So that means reverting the change that I thought would improve the situation: https://github.com/nicoespeon/abracadabra/commit/1cfac73bf8de14edb77cdb8cdd523d7d1b37cd5a

My understanding was that "onStartupFinished" would indeed trigger every time but won't delay the editor startup vs. "onLanguage" could delay the startup if a JS/TS file was already open in the project. Did I understand that wrong and actually made the situation worse?

**Comment by tjx666** [comment]
One problem onStartupFinished cause this extension will be actived every time the vscode startup even you open a empty workspace. Because you run all the modules synchronously

**Comment by nicoespeon** [comment]
Got it, thanks for the details. Let's go with this improvement. Further improvements would be to go for the lazy loading, as you mentioned. Or we should also measure what takes so long and optimize that.

But this is acceptable to me so far.

**Pull request merged**
