### PR TITLE
Introduce "Create Class" Refactor

### PR DESCRIPTION
**Pull request by 11joselu**
Create a class without constructor:

https://user-images.githubusercontent.com/8685132/186938150-21cfd33d-6307-4129-9f86-a9003f65875d.mp4

Create a class with primitives values

https://user-images.githubusercontent.com/8685132/186938675-bd60fb62-66e6-4aa8-8353-008e4dd4c826.mp4

Create a class injecting declared variables (inferred names)

https://user-images.githubusercontent.com/8685132/186939024-309aa4bf-d70c-4068-b3da-a5a68d1a882c.mp4

Create a multiple class (only works from left-to-right).

https://user-images.githubusercontent.com/8685132/186939265-544b5387-47f0-419e-90b0-2186d55d66c1.mp4

### CODE REVIEW

**Comment by 11joselu** [comment]
I changed a little because is generating a bad result when the undefined class is inside a function or method:

Inside a Function or curry functions

https://user-images.githubusercontent.com/8685132/186960398-86bb1f17-06e8-4789-9793-74df665ed61d.mp4

Fixed too creating class in a method (class and literal objects)

https://user-images.githubusercontent.com/8685132/186960538-bce28949-36fa-478a-9753-a60ea42e5c6d.mp4

**Comment by 11joselu** [comment]
Hey @nicoespeon any feedback is welcome :)

**Comment by nicoespeon** [comment]
Thanks for pinging @11joselu, I missed the notification last Saturday! I will have a look this weekend.

Shout-outs for all the recordings you made! I didn't watch them yet, but that looks dope :smi

**Comment by 11joselu** [comment]
@nicoespeon any news?

**Comment by nicoespeon** [comment]
@11joselu sorry, I know I'm terribly late on this. I have a lot of things to do for Sept 28th so kind of underwater for the moment and putting Abracadabra on the side.

Overall this looks great! 

I need to check why CI is failing now. I'm not sure it's related to this PR, but something has broken with TS.

Technically, this kind of transformation isn't a "refactoring" in the sense that it does change what the code is doing. In fact, that's why I created that other extension [Hocus Pocus](https://github.com/nicoespeon/hocus-pocus). But I recognize having to deal with different extensions is annoying and this is helpful behavior. I still need to make up my mind around this, will do it once I'm good with my other priorities.

One thing I'm wondering: would it create a new class even if the class exists already? 

Thanks for being patient on this. I know it has been a while already since this is sitting here.

**Comment by 11joselu** [comment]
@nicoespeon 
> One thing I'm wondering: would it create a new class even if the class exists already?

No. It detects if the class has been declared so should not create another definition of it. There are a test case for that case

> Technically, this kind of transformation isn't a "refactoring" in the sense that it does change what the code is doing. In fact, that's why I created that other extension [Hocus Pocus](https://github.com/nicoespeon/hocus-pocus). But I recognize having to deal with different extensions is annoying and this is helpful behavior. I still need to make up my mind around this, will do it once I'm good with my other priorities.

Ohh I didn't know about Hocus Pocus. I think the create class behavior from that that extension solve my "issue". **If you want feel free to close this PR because I will use it from Hocus Pocus** :)

**Comment by nicoespeon** [comment]
@11joselu so, I finally delivered my talk, which means I will have some free time again. I'll review the PR tomorrow and see what to do—I'm balancing about bringing Hocus Pocus back in Abracadabra for convenience, despite the scope is slightly different.

**Comment by nicoespeon** [comment]
Well, well, well, it took me a while, sorry for that!

So yeah, I double-checked what this was doing and it's completely covered with [what Hocus Pocus can do](https://github.com/nicoespeon/hocus-pocus#create-class). Thus, I'll close this PR but still want to thank you for contributing. Your PR was great with clear tests and docs. So I'll credit you for that anyway ;-)

**Comment by 11joselu** [comment]
> Well, well, well, it took me a while, sorry for that!
> 
> So yeah, I double-checked what this was doing and it's completely covered with [what Hocus Pocus can do](https://github.com/nicoespeon/hocus-pocus#create-class). Thus, I'll close this PR but still want to thank you for contributing. Your PR was great with clear tests and docs. So I'll credit you for that anyway ;-)

No problem!. Thanks for your time 😄

**Pull request closed without merging**
